### ISSUE TITLE
[Bug]: Cypress tests not created

### ISSUE THREAD

**Issue by iluwatar** [kubeshop/testkube-argocd#6]
### Contact Details

ilkka.seppala@gofore.com

### What happened?

I followed the instructions in README.md to setup Argo CD to work with Testkube. In the final step, I point the testkube-tests application to a Github repository folder that contains Cypress tests, but the tests are not being created. It can be reproduced with these parameters:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testkube-tests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kubeshop/testkube-executor-cypress.git
    targetRevision: HEAD
    path: examples
    plugin:
      name: testkube
  destination:
    server: https://kubernetes.default.svc
    namespace: testkube

```

On the other hand, if I point the application to a repository and folder containing postman tests, it seems to work. For example, the examples/postman-collections folder of this repository.

### Version

1.0.0 (Edge)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
